import type { ProjectFile } from './analyze';

// Un RPG chico en Godot para probar VibeMap sin subir nada.
const gd = (lines: string[]) => lines.join('\n') + '\n';

export const rpgSample: ProjectFile[] = [
  { path: 'project.godot', content: gd(['[application]', 'config/name="Mini RPG"', 'run/main_scene="res://scenes/main.tscn"', '', '[autoload]', 'SaveSystem="*res://scripts/save_system.gd"']) },
  { path: 'scenes/main.tscn', content: gd(['[gd_scene load_steps=2 format=3]', '[ext_resource type="Script" path="res://scripts/main.gd" id="1"]', '[node name="Main" type="Node2D"]', 'script = ExtResource("1")']) },
  { path: 'scripts/main.gd', content: gd([
    'extends Node2D',
    '',
    'const PlayerScene = preload("res://scripts/player.gd")',
    'const Hud = preload("res://scripts/ui/hud.gd")',
    '',
    'var player: Player',
    'var battle: BattleManager',
    '',
    'func _ready() -> void:',
    '\tplayer = Player.new()',
    '\tadd_child(player)',
    '\tvar data := SaveSystem.load_game()',
    '\tplayer.restore(data)',
    '\tbattle = BattleManager.new()',
    '\tadd_child(battle)',
    '\tbattle.battle_ended.connect(_on_battle_ended)',
    '\tbattle.start(player)',
    '\tvar hud := Hud.new()',
    '\tadd_child(hud)',
    '\thud.bind(player)',
    '',
    'func _unhandled_input(event: InputEvent) -> void:',
    '\tif event.is_action_pressed("attack"):',
    '\t\tbattle.player_attack(6)',
    '\telif event.is_action_pressed("use_item"):',
    '\t\tplayer.use_item(0, battle.enemy)',
    '',
    'func _on_battle_ended(won: bool) -> void:',
    '\tif won:',
    '\t\tplayer.gain_xp(40)',
    '\tSaveSystem.save_game(player.snapshot())',
  ]) },
  { path: 'scripts/player.gd', content: gd([
    'class_name Player',
    'extends CharacterBody2D',
    '',
    'signal hp_changed(value: int)',
    '',
    'var hp := 30',
    'var xp := 0',
    'var inventory := Inventory.new()',
    '',
    'func _ready() -> void:',
    '\tinventory.add_item(Pokeball.new())',
    '',
    'func take_damage(amount: int) -> void:',
    '\thp = max(hp - amount, 0)',
    '\thp_changed.emit(hp)',
    '',
    'func gain_xp(amount: int) -> void:',
    '\txp += amount',
    '',
    'func use_item(index: int, target: Enemy) -> bool:',
    '\tvar item := inventory.take(index)',
    '\treturn item != null and item.use(target)',
    '',
    'func snapshot() -> Dictionary:',
    '\treturn {"hp": hp, "xp": xp, "items": inventory.names()}',
    '',
    'func restore(data: Dictionary) -> void:',
    '\thp = data.get("hp", hp)',
    '\txp = data.get("xp", xp)',
  ]) },
  { path: 'scripts/inventory.gd', content: gd([
    'class_name Inventory',
    'extends RefCounted',
    '',
    'var items: Array[Item] = []',
    '',
    'func add_item(item: Item) -> void:',
    '\titems.append(item)',
    '',
    'func take(index: int) -> Item:',
    '\tif index < 0 or index >= items.size():',
    '\t\treturn null',
    '\treturn items.pop_at(index)',
    '',
    'func names() -> Array:',
    '\treturn items.map(func(i): return i.label)',
  ]) },
  { path: 'scripts/items/item.gd', content: gd([
    'class_name Item',
    'extends RefCounted',
    '',
    'var label := "Objeto"',
    '',
    'func use(_target) -> bool:',
    '\treturn false',
  ]) },
  { path: 'scripts/items/pokeball.gd', content: gd([
    'class_name Pokeball',
    'extends Item',
    '',
    'func _init() -> void:',
    '\tlabel = "Pokeball"',
    '',
    'func use(target) -> bool:',
    '\tif target is Enemy and target.hp_ratio() < 0.3:',
    '\t\ttarget.capture()',
    '\t\treturn true',
    '\treturn false',
  ]) },
  { path: 'scripts/battle_manager.gd', content: gd([
    'class_name BattleManager',
    'extends Node',
    '',
    'signal battle_ended(won: bool)',
    '',
    'var enemy: Enemy',
    '',
    'func start(player: Player) -> void:',
    '\tenemy = Enemy.new()',
    '\tplayer.hp_changed.connect(_on_player_hp)',
    '',
    'func player_attack(damage: int) -> void:',
    '\tenemy.take_damage(damage)',
    '\tif enemy.is_defeated():',
    '\t\tbattle_ended.emit(true)',
    '',
    'func _on_player_hp(value: int) -> void:',
    '\tif value == 0:',
    '\t\tbattle_ended.emit(false)',
  ]) },
  { path: 'scripts/enemy.gd', content: gd([
    'class_name Enemy',
    'extends Node2D',
    '',
    'var hp := 20',
    'var max_hp := 20',
    'var captured := false',
    '',
    'func take_damage(amount: int) -> void:',
    '\thp = max(hp - amount, 0)',
    '',
    'func hp_ratio() -> float:',
    '\treturn float(hp) / max_hp',
    '',
    'func capture() -> void:',
    '\tcaptured = true',
    '',
    'func is_defeated() -> bool:',
    '\treturn hp == 0 or captured',
  ]) },
  { path: 'scripts/ui/hud.gd', content: gd([
    'extends CanvasLayer',
    '',
    'var label := Label.new()',
    '',
    'func bind(player: Player) -> void:',
    '\tadd_child(label)',
    '\tplayer.hp_changed.connect(_on_hp_changed)',
    '\t_on_hp_changed(player.hp)',
    '',
    'func _on_hp_changed(value: int) -> void:',
    '\tlabel.text = "HP %d" % value',
  ]) },
  { path: 'scripts/save_system.gd', content: gd([
    'extends Node',
    '',
    'const PATH := "user://partida.json"',
    '',
    'func save_game(data: Dictionary) -> void:',
    '\tvar file := FileAccess.open(PATH, FileAccess.WRITE)',
    '\tfile.store_string(JSON.stringify(data))',
    '',
    'func load_game() -> Dictionary:',
    '\tif not FileAccess.file_exists(PATH):',
    '\t\treturn {}',
    '\treturn JSON.parse_string(FileAccess.open(PATH, FileAccess.READ).get_as_text())',
  ]) },
];
